### ISSUE TITLE
block-grid columns are not collapsing in Gmail app

### ISSUE THREAD

**Issue by RafaelFunchal** [zurb/foundation-emails#118]
Hey guys!

First, thank you for all your work. I really like all Zurb tools.

About my issue: I'm creating an email using `block-grid` because it has to be responsive in Gmail app, but the columns are not collapsing.

I'm following the doc:

```html
<table class="container">
  <tr>
    <td>

      <table class="block-grid two-up">
        <tr>
          <td>

            Column #1

          </td><td> <!-- Make sure the tags are directly next to each other -->

            Column #2

          </td>
        </tr>
      </table>

    </td>
  </tr>
</table>
```
and I already inserted the media query:

```CSS
@media only screen and (max-width: 600px) {
  table[class="container"] .block-grid td {
    width: 100% !important;
  }
}
```

Can you help me?
