### ISSUE TITLE
cdnjs 1.0.5 version is actually 1.0.4

### ISSUE THREAD

**Issue by whatnickcodes** [zurb/foundation-emails#131]
I was working off the cdnjs URL: http://cdnjs.com/libraries/zurb-ink

I was about to send a pull requests for two things:

To add: 
```css
p.center {
  text-align: center;
}
```

And to add `display: block;` to:

```css
table.button td a,
table.tiny-button td a,
table.small-button td a,
table.medium-button td a,
table.large-button td a {
    display: block;
}
```

While prepping the Pull Requests, I saw that the code was already there! Which is pretty cool because it means my Pull Request would have been a solid contribution if it wasn't already done.

Thought you guys should know so you can get your update on CDN.js.
