### ISSUE TITLE
Simplify lines of text that aren't part of a common block.

### ISSUE THREAD

**Issue by paxperscientiam** [zurb/foundation-emails#157]
This is just a feature request. It would be great to see ink Inky 2 an easier way to justify multiple lines of text that do not share a common block.

EDIT: title should read "Simplify justifying lines of text that aren't part of a common block

**Comment by rafibomb** [comment]
Sorry, can you describe how this would help?

**Comment by paxperscientiam** [comment]
This is really a typsetting problem, though it's motivated by branding. A logotype might feature two lines of text that are relatively justified, which would thus aesthetically disallow line or word breaks.

Now, I say "relative" because maybe the designer only wants this logotype to occupy 1/3 of the row-width.

Client support on this front is pretty spotty and requires hack-y methods to work across the client landscape (for the most part). It would be enormously helpful if foundation-emails incorporated some sort of solution for this.

That's the use-case, but I honestly don't know how in-demand this might be.'

EDIT: You know what, I'm gonna take a whack at this and hopefully submit a PR.

**Comment by paxperscientiam** [comment]
@rafibomb 

OK, so the below won't work for Safari, hence the 'center' fallback. Also, there is no way this would work in most email clients. What do you think about using something like this, perhaps with more polish, in Foundation 6?

EDIT: fixed HTML

``` html
 <table class="row">
               <tr>
                <td class="wrapper">
 <table class="justify logo two columns">
                  <tr>
                   <td class="panel">
                    w a t e r <span style="color:red">w a r s</span>
                   </td>
                   <td class="expander"></td>
                  </tr>
                  <tr>
                   <td class="log panel">
                    Water, water everywhere, but not a drop to drink.
                   </td>
                   <td class="expander"></td>
                  </tr>
                 </table>
 </td>
               </tr>
```

``` css
table.justify td {
 text-align: -webkit-center;
 text-align-last: justify;
 -moz-text-align-last:justify;
  overflow: hidden;
 white-space: nowrap;
 }
.justify.logo tr:nth-of-type(1) {
 text-transform:uppercase;
}
.justify.logo tr:nth-of-type(2) td:nth-of-type(1) {
 font-size:0.86em;
}
```
